### ISSUE TITLE
Carb entry uses "Premeal" preset icon

### ISSUE THREAD

**Issue by jgefaell** [LoopKit/LoopCaregiver#15]
I mentioned this during the LnL Zoom the other day. I'm opening an issue to track this. The carb entry icon should be the same as in the Loop app.

**Comment by gestrich** [comment]
Thanks for reporting @jgefaell. This was fixed in a merge to dev earlier today so I'll close this one out https://loop.zulipchat.com/#narrow/stream/358458-Loop-Caregiver-App/topic/Updates/near/390503770
