### ISSUE TITLE
Custom Bundle ID requires CAREGIVER_APP_BUNDLE_IDENTIFIER

### ISSUE THREAD

**Issue by jgefaell** [LoopKit/LoopCaregiver#5]
To customize the Bundle ID, you must add CAREGIVER_APP_BUNDLE_IDENTIFIER to the override file. MAIN_APP_BUNDLE_IDENTIFIER is not used.

e.g.
```
// Override this if you don't want the default com.${DEVELOPMENT_TEAM}.loopkit that loop uses
//MAIN_APP_BUNDLE_IDENTIFIER =
CAREGIVER_APP_BUNDLE_IDENTIFIER = com.domain.caregiver
```

**Comment by billybooth** [comment]
Thanks @jgefaell. What you've described above was known, but there's no harm adding an example to the override file that we ship with this repository. Created [PR #7](https://github.com/LoopKit/LoopCaregiver/pull/7) to address the concern raised here.
